"""removed some users table column

Revision ID: 44412dfde784
Revises: 3df28553d559
Create Date: 2026-07-30 12:45:14.451706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44412dfde784'
down_revision = '3df28553d559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credits_used')
        batch_op.drop_column('recharged_credits')
        batch_op.drop_column('tier')
        batch_op.drop_column('last_credit_reset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_credit_reset', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('recharged_credits', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('credits_used', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
