"""added the tier, recharge_credits, and others

Revision ID: 894fe3afffb3
Revises: 44412dfde784
Create Date: 2026-07-30 13:12:24.916944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894fe3afffb3'
down_revision = '44412dfde784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recharged_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credits_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_credit_reset', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_credit_reset')
        batch_op.drop_column('credits_used')
        batch_op.drop_column('recharged_credits')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
