"""removed index from user_id columns

Revision ID: c68908522243
Revises: 61d55eab0cbb
Create Date: 2026-07-30 14:54:18.040099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68908522243'
down_revision = '61d55eab0cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generations_user_id'))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
